email: hello@regularsmarketing.com
instagram: "@regularsmarketing"
instagram_url: https://instagram.com/regularsmarketing
response_time: Within 1 day
works_with: Independent restaurants & cafés and other small businesses ready to
  get regulars
hours:
  - days: Monday – Friday
    hours: 9:00am – 6:00pm
  - days: Saturday
    hours: By appointment
  - days: Sunday
    hours: Closed
